### PR TITLE
Fix Snappy/S2 block fallback max size

### LINKED ISSUE #14: Decode errors out on large block compressed with Snappy
Question concerning this code:
https://github.com/minio/minlz/blob/5701124dd9d5382f6f7798042e40f17a04f4572f/decode.go#L60

Why subject a Snappy/S2 block to the MinLZ block limit?

It would be nice to be able to compress blocks within the limit with MinLZ and larger blocks using Snappy and be able to use `minlz.Decode` for both.

### PR DESCRIPTION
**Pull request by klauspost**
Allow bigger S2/Snappy blocks.

Fixes #14

### CODE REVIEW

File: decode.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func Decode(dst, src []byte) ([]byte, error) {
 	}
 
 	if !isMLZ {
-		if l, _ := s2.DecodedLen(block); l > MaxBlockSize {
```
Comment (RaduBerinde) [inline decode.go:61]: Why not let `s2.Decode()` handle it?

Comment (klauspost) [reply decode.go:61]: Mainly because I don't want to forward another error type. So I will have to handle it separately anyway.

**Review by RaduBerinde — APPROVED** [review]
LGTM, thanks!

**Review by harshavardhana — APPROVED** [review]
